import { jsPDF } from 'jspdf';
import 'jspdf-autotable';

interface Session {
  id: string;
  date: string;
  mode: string;
  duration: number;
  task: string;
  interruptions: number;
}

interface DailyStats {
  date: string;
  sessions: number;
  focusMinutes: number;
  interruptions: number;
}

interface Task {
  id: string;
  name: string;
  estimatedPomodoros: number;
  completedPomodoros: number;
  done: boolean;
}

declare module 'jspdf' {
  interface jsPDF {
    autoTable: (options: any) => jsPDF;
  }
}

export const exportToPDF = (
  sessions: Session[],
  dailyStats: DailyStats[],
  tasks: Task[],
  currentStreak: number,
  longestStreak: number
) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Title
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Pomodoro Focus Report', pageWidth / 2, 20, { align: 'center' });

  // Date
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated on ${new Date().toLocaleDateString()}`, pageWidth / 2, 30, { align: 'center' });

  // Summary Section
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', 14, 50);

  const totalSessions = sessions.filter(s => s.mode === 'work').length;
  const totalFocusMinutes = dailyStats.reduce((sum, stat) => sum + stat.focusMinutes, 0);
  const totalInterruptions = dailyStats.reduce((sum, stat) => sum + stat.interruptions, 0);
  const tasksCompleted = tasks.filter(t => t.done).length;

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  
  const summaryData = [
    ['Total Focus Sessions', totalSessions.toString()],
    ['Total Focus Time', `${Math.floor(totalFocusMinutes / 60)}h ${totalFocusMinutes % 60}m`],
    ['Total Interruptions', totalInterruptions.toString()],
    ['Tasks Completed', tasksCompleted.toString()],
    ['Current Streak', `${currentStreak} days`],
    ['Longest Streak', `${longestStreak} days`],
  ];

  doc.autoTable({
    startY: 55,
    head: [['Metric', 'Value']],
    body: summaryData,
    theme: 'striped',
    headStyles: { fillColor: [239, 83, 80] },
    margin: { left: 14, right: 14 },
  });

  // Daily Stats Section
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Daily Statistics (Last 30 Days)', 14, doc.internal.pageSize.getHeight() > 150 ? 120 : 100);

  const last30Days = dailyStats.slice(-30).reverse();
  const dailyData = last30Days.map(stat => [
    new Date(stat.date).toLocaleDateString(),
    stat.sessions.toString(),
    `${stat.focusMinutes} min`,
    stat.interruptions.toString(),
  ]);

  doc.autoTable({
    startY: doc.internal.pageSize.getHeight() > 150 ? 125 : 105,
    head: [['Date', 'Sessions', 'Focus Time', 'Interruptions']],
    body: dailyData,
    theme: 'striped',
    headStyles: { fillColor: [239, 83, 80] },
    margin: { left: 14, right: 14 },
  });

  // Recent Sessions Section (if space)
  if (sessions.length > 0) {
    doc.addPage();
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Recent Sessions', 14, 20);

    const recentSessions = sessions.slice(-50).reverse();
    const sessionData = recentSessions.map(session => [
      new Date(session.date).toLocaleDateString(),
      session.mode === 'work' ? 'Focus' : session.mode === 'shortBreak' ? 'Short Break' : 'Long Break',
      `${Math.round(session.duration / 60)} min`,
      session.task || 'No task',
      session.interruptions.toString(),
    ]);

    doc.autoTable({
      startY: 25,
      head: [['Date', 'Type', 'Duration', 'Task', 'Interruptions']],
      body: sessionData,
      theme: 'striped',
      headStyles: { fillColor: [239, 83, 80] },
      margin: { left: 14, right: 14 },
    });
  }

  // Tasks Section (if space)
  if (tasks.length > 0) {
    doc.addPage();
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('Tasks', 14, 20);

    const taskData = tasks.map(task => [
      task.name,
      task.estimatedPomodoros.toString(),
      task.completedPomodoros.toString(),
      task.done ? '✓ Done' : 'In Progress',
    ]);

    doc.autoTable({
      startY: 25,
      head: [['Task', 'Estimated', 'Completed', 'Status']],
      body: taskData,
      theme: 'striped',
      headStyles: { fillColor: [239, 83, 80] },
      margin: { left: 14, right: 14 },
    });
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(128, 128, 128);
    doc.text(
      `Page ${i} of ${pageCount} | Generated by Pomodoro Focus`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
  }

  // Save
  doc.save(`pomodoro-report-${new Date().toISOString().split('T')[0]}.pdf`);
};

export const exportToCSV = (
  sessions: Session[],
  dailyStats: DailyStats[],
  tasks: Task[]
) => {
  // Sessions CSV
  const sessionsCSV = [
    ['Date', 'Type', 'Duration (min)', 'Task', 'Interruptions'],
    ...sessions.map(s => [
      new Date(s.date).toLocaleDateString(),
      s.mode === 'work' ? 'Focus' : s.mode === 'shortBreak' ? 'Short Break' : 'Long Break',
      Math.round(s.duration / 60).toString(),
      s.task || '',
      s.interruptions.toString(),
    ]),
  ].map(row => row.join(',')).join('\n');

  // Daily Stats CSV
  const dailyCSV = [
    ['Date', 'Sessions', 'Focus Minutes', 'Interruptions'],
    ...dailyStats.map(s => [
      s.date,
      s.sessions.toString(),
      s.focusMinutes.toString(),
      s.interruptions.toString(),
    ]),
  ].map(row => row.join(',')).join('\n');

  // Tasks CSV
  const tasksCSV = [
    ['Task', 'Estimated Pomodoros', 'Completed Pomodoros', 'Status'],
    ...tasks.map(t => [
      t.name,
      t.estimatedPomodoros.toString(),
      t.completedPomodoros.toString(),
      t.done ? 'Done' : 'In Progress',
    ]),
  ].map(row => row.join(',')).join('\n');

  // Download sessions
  downloadCSV(sessionsCSV, 'pomodoro-sessions.csv');
  
  // Download daily stats after a delay
  setTimeout(() => downloadCSV(dailyCSV, 'pomodoro-daily-stats.csv'), 500);
  
  // Download tasks after another delay
  setTimeout(() => downloadCSV(tasksCSV, 'pomodoro-tasks.csv'), 1000);
};

const downloadCSV = (csv: string, filename: string) => {
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
